### ISSUE TITLE
Attribute name mismatch in "usable_CDs"

### ISSUE THREAD

**Issue by klingo** [watchyoursixx/HunterSimWotLK#18]
There is a name mismatch of the "berserk/ing" attribute between these two files:
https://github.com/watchyoursixx/HunterSimWotLK/blob/de2aeba22f6567177db33c4197da8272999151d0/js/ui/settingsui.js#L566
https://github.com/watchyoursixx/HunterSimWotLK/blob/de2aeba22f6567177db33c4197da8272999151d0/js/data/auras.js#L1403

**Comment by watchyoursixx** [comment]
fixed in #20
