### ISSUE TITLE
"storeData" is called before "fetchData" is complete, which causes SavedSets to be reset

### ISSUE THREAD

**Issue by klingo** [watchyoursixx/HunterSimWotLK#19]
### Problem Statement:
The "setItem" function is called first, and only afterwards the "getItem", which causes the "localStorage.sets" to be reset every time the page is reloaded.
https://github.com/watchyoursixx/HunterSimWotLK/blob/4adba82080fb1fefbd6d4983733f8bc1d24f667d/js/ui/datastorage.js#L71
https://github.com/watchyoursixx/HunterSimWotLK/blob/de2aeba22f6567177db33c4197da8272999151d0/js/ui/datastorage.js#L261

### Debugging the issue:
In the **fetchData** function, before the stored sets are read here:
https://github.com/watchyoursixx/HunterSimWotLK/blob/de2aeba22f6567177db33c4197da8272999151d0/js/ui/datastorage.js#L261
... the "selectTalents" function is called here:
https://github.com/watchyoursixx/HunterSimWotLK/blob/4adba82080fb1fefbd6d4983733f8bc1d24f667d/js/ui/datastorage.js#L213
This then calls the following function:
https://github.com/watchyoursixx/HunterSimWotLK/blob/7f0197c50780cef836a5e06ae876b0fdb9c7b4a6/js/ui/settingsui.js#L486
which in turn calls the **storeData** function here:
https://github.com/watchyoursixx/HunterSimWotLK/blob/7f0197c50780cef836a5e06ae876b0fdb9c7b4a6/js/ui/settingsui.js#L52

This causes the **storeData** function to be executed, before the **fetchData** function is fully executed, and thus in turn resets the SavedSets every time.

**Comment by watchyoursixx** [comment]
fixed in #20
